### ISSUE TITLE
Replace youtube-dl with yt-dlp

### ISSUE THREAD

**Issue by ghost** [yausername/dvd#27]
Related issue, which should be implemented or closed to close this issue: https://github.com/yausername/youtubedl-android/issues/117

**Comment by Pentaphon** [comment]
@yausername please make this happen

**Comment by xibr** [comment]
To fix throttle downloads, I have updated youtube-dl binary https://github.com/yausername/youtubedl-lazy/releases/download/2021.06.06/youtube_dl.zip To apply the changes you must remove the app data and then update youtube-dl from the app.

**Comment by sebma** [comment]
@xibr The youtube-dl project seems dead since the end of june 2021 : https://github.com/ytdl-org/youtube-dl/graphs/commit-activity.

Can you please replace `youtube-dl` by [`yt-dlp`](https://github.com/ytdl-org/youtube-dl) (it has the same syntax) ?

**Comment by xibr** [comment]
I apply the patch to [youtubedl-lazy](https://github.com/yausername/youtubedl-lazy) from [[YouTube] Unthrottle downloads by responding to the "n" parameter challenge #30184](https://github.com/ytdl-org/youtube-dl/pull/30184) 
also we have created a branch to [switch-to-yt-dlp](https://github.com/xibr/youtubedl-android/tree/switch-to-yt-dlp)
https://github.com/yausername/youtubedl-android/pull/120
Even if I change to yt-dlp in [youtubedl-android](https://github.com/yausername/youtubedl-android) I can't do anything in this repository because I don't have write access and the repository owner is inactive.

**Comment by Pentaphon** [comment]
@xibr make a fork so we can use yours instead

**Comment by xibr** [comment]
@sebma @Pentaphon 
debug apk 
[app-arm64-v8a-debug.apk](https://github.com/xibr/xibr.github.io/raw/master/dvd/app-arm64-v8a-debug.apk)
[app-armeabi-v7a-debug.apk](https://github.com/xibr/xibr.github.io/raw/master/dvd/app-armeabi-v7a-debug.apk)
[app-x86-debug.apk](https://github.com/xibr/xibr.github.io/raw/master/dvd/app-x86-debug.apk)
[app-x86_64-debug.apk](https://github.com/xibr/xibr.github.io/raw/master/dvd/app-x86_64-debug.apk)
or build your one from this branch [https://github.com/xibr/dvd/tree/switch-to-yt-dlp](https://github.com/xibr/dvd/tree/switch-to-yt-dlp)

**Comment by yausername** [comment]
> Even if I change to yt-dlp in [youtubedl-android](https://github.com/yausername/youtubedl-android) I can't do anything in this repository because I don't have write access and the repository owner is inactive.

added you as a collaborator

**Comment by sebma** [comment]
Related : [PR #123](https://github.com/yausername/youtubedl-android/pull/123)

**Comment by ntnguyen1234** [comment]
I'm glad the project has switched to yt-dlp. Since yt-dlp supports download in multithread (`--concurrent-fragments` - [https://github.com/yt-dlp/yt-dlp#download-options](https://github.com/yt-dlp/yt-dlp#download-options)). Could this feature be implemented in dvd (like an option in the settings)? Tks a lot.
