### ISSUE TITLE
Cannot download after updating yt-dlp

### ISSUE THREAD

**Issue by StaringtheStar** [yausername/dvd#86]
After updating yt-dlp to the latest version(2023.01.06), I can't download any videos. Only solution for now is just reinstalling and not updating yt-dlp.

**Comment by mario0318** [comment]
Same issue here. Though to be more precise, the problem seems to be one where no results come up whatsoever. It merely shows the loading icon for a brief moment and it remains on the same page with no video results populating on screen as otherwise expected. This is occurring with ANY website whether via Share link or by inputting address directly in the app. It all proves the same.

**Comment by mario0318** [comment]
So my current workaround was uninstalling and thru F-Droid finding an older version to install. I had to go from 0.1.5.10504 > 0.1.4.10404. Both dvd packages (armv7, arm64) version 0.1.5.x encounter the issue I posted.

Reverting to dvd 0.1.4.x which utilizes yt-dlp 2022.08.14 is functioning as normal and can confirm to have no issues displaying results and downloading videos. 

I suspect the problem may be related to yt-dlp and the library released early January (2023.01.06), since I recall using the latest 0.1.5.x dvd app with no such problem at any time prior to updating yt-dlp thru dvd settings menu.

**Comment by StaringtheStar** [comment]
It seems yt-dlp was the issue, since re-installing the app (and not updating yt-dlp) had no problem. This was also confirmed at [youtube-android-example](https://github.com/yausername/youtubedl-android/releases).
As for now, yt-dlp's latest release(2023.02.17.) fixes the problem, thus closing this issue.
